### ISSUE TITLE
Switching from http to https protocol?

### ISSUE THREAD

**Issue by alexis-michaud** [langsci/userWebsiteSettings#1]
(Apologies in case this is not the right place to open this Issue)

Computer science colleagues & students say we should switch from http to https for our archive, the [Pangloss Collection](http://lacito.vjf.cnrs.fr/pangloss/index_en.html), otherwise our website will continue to be an easy prey for hackers who can then use the website for their intents & purposes. 

The risk seems real, even though there are no commercial transactions on the website and no user identification: basically making materials available for download, like the langsci-press website. We've planned the transition to https for the next overhaul to the website (tentatively scheduled for this academic year, 2018-2019).

Is this transition necessary for the langsci-press website, too?

**Comment by Glottotopia** [comment]
You are correct to point out these security issues. @CFanselow would be the person in charge on our side for https, but I am not sure what the current plans are.

**Comment by alexis-michaud** [comment]
Now done! :+1:
